### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by Tphilus** [Tphilus/React_Full_Course#7]

**Comment by Tphilus** [comment]
How to to solve the project 6 
replace the useState with the useContext

**Comment by Tphilus** [comment]
Cannot read properties of undefined (reading 'reduce')
TypeError: Cannot read properties of undefined (reading 'reduce')
    at HeaderCartButton (http://localhost:3000/static/js/bundle.js:452:42)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:22481:22)
    at updateFunctionComponent (http://localhost:3000/static/js/bundle.js:25363:24)
    at beginWork (http://localhost:3000/static/js/bundle.js:27075:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:12073:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:12117:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:12174:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:32048:11)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:31295:16)
    at workLoopSync (http://localhost:3000/static/js/bundle.js:31218:9)

FOOD ADD
